### PR TITLE
remove memoize-sync

### LINKED ISSUE #7: memoize-sync is broken or something
```
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! version not found: memoize-sync@0.0.2
```

... do we even need it?

### PR DESCRIPTION
**Pull request by stephenmathieson**
@dominicbarnes @matthewmueller 

this is blocking atm... cant deploy because duo is broken

closes #7, ref https://github.com/duojs/duo/issues/506

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Probably just best to switch to v2.0.0

**Comment by stephenmathieson** [comment]
idk if 2.0.0 works, nor do i even know why we use this thing

**Comment by stephenmathieson** [comment]
plus 0.0.2 -> 2.0.0 is a huge bump im not comfortable making for no apparent reason

**Comment by dominicbarnes** [comment]
I guess we can ditch it, but it's saving us CPU cycles when we're parsing dependencies. The tests we have should confirm whether or not it still works.

**Pull request merged**
